"""
Smoke test for the committed crop-recommendation model (run with
`python tests/smoke_test.py`).

Loads the serialized scikit-learn pipeline (StandardScaler + SVC) exactly as a
consumer would and confirms the whole predict path is wired and compatible with
the installed library versions: the pipeline is fitted, expects the seven
documented agronomic features in the right order, and returns a valid encoded
crop class for a plausible input row.

The training dataset is generated by `notebooks/01_data_generation.ipynb` and is
intentionally not committed (see .gitignore), so this is a load / compatibility
guard, NOT an accuracy or generalization check.
"""

import pickle
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
MODEL_PATH = ROOT / "models" / "best_model_crop.pkl"

# The feature contract the notebooks train on, in order.
FEATURE_COLUMNS = ["N", "P", "K", "temperature", "humidity", "ph", "rainfall"]

# A few agronomically plausible rows (not from the training set) to exercise predict().
SAMPLE_ROWS = [
    [90, 42, 43, 20.9, 82.0, 6.5, 202.9],
    [20, 67, 20, 23.0, 60.0, 6.8, 60.0],
    [40, 72, 77, 17.0, 16.9, 7.5, 88.5],
]


def main() -> int:
    with open(MODEL_PATH, "rb") as f:
        model = pickle.load(f)

    # Fitted pipeline with the expected feature contract.
    assert hasattr(model, "predict"), "loaded object is not a predictor"
    assert getattr(model, "n_features_in_", None) == len(FEATURE_COLUMNS), (
        f"expected {len(FEATURE_COLUMNS)} features, got {getattr(model, 'n_features_in_', None)}"
    )
    names = list(getattr(model, "feature_names_in_", []))
    assert names == FEATURE_COLUMNS, f"feature name/order mismatch: {names}"

    # Pass a DataFrame with the right column names so no feature-name warning fires.
    X = pd.DataFrame(SAMPLE_ROWS, columns=FEATURE_COLUMNS)
    preds = model.predict(X)

    assert len(preds) == len(SAMPLE_ROWS), "prediction count mismatch"
    valid = set(model.classes_)
    assert set(preds).issubset(valid), f"predictions outside known classes: {set(preds) - valid}"

    print(
        f"OK: pipeline={type(model).__name__}, features={names}, "
        f"{len(valid)} crop classes, sample predictions={list(preds)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
